# Create NumPy arrays

In [34]:
import numpy as np

In [35]:
nums = [[1,2,3], [4,5,6]]

In [36]:
nums = np.array(nums)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
nums.ndim

2

In [38]:
nums.shape

(2, 3)

In [39]:
nums.dtype

dtype('int32')

In [40]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [41]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [43]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [45]:
np.diag(arr)

array([1, 2, 3, 4])

In [46]:
rand_arr = np.random.randint(1,15,4)
rand_arr

array([2, 9, 6, 2])

In [47]:
rand_arr = np.random.rand(4)
rand_arr

array([0.43051296, 0.08267807, 0.80636949, 0.54538914])

In [48]:
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.40756015, 0.16526005, 0.75903314],
       [0.01226589, 0.47615714, 0.86500462]])

In [49]:
rand_arr = np.random.randn(4)
rand_arr

array([-1.2233223 , -0.60847249, -1.30755072,  2.23108339])

In [50]:
np.mean(rand_arr)

-0.22706553178592703

In [51]:
arr = np.random.randint(1,100,20)
arr

array([64, 46, 38, 61, 37, 91, 31, 27, 78,  5, 85, 71, 27, 61, 93, 60, 61,
       69, 97,  7])

In [52]:
arr.shape

(20,)

In [53]:
arr = arr.reshape(2,10)
arr

array([[64, 46, 38, 61, 37, 91, 31, 27, 78,  5],
       [85, 71, 27, 61, 93, 60, 61, 69, 97,  7]])

In [54]:
arr.shape

(2, 10)

In [55]:
arr.ndim

2

In [56]:
arr = arr.reshape(20)
arr.ndim

1

In [59]:
arr = arr.reshape(2,2,5)
arr

array([[[64, 46, 38, 61, 37],
        [91, 31, 27, 78,  5]],

       [[85, 71, 27, 61, 93],
        [60, 61, 69, 97,  7]]])

In [60]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
ar.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [64]:
ar.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [63]:
ar.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
np.random.seed(12)
a = np.random.randint(1,101,15).reshape(3,5)
a

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35]])

In [69]:
a.size

15